name: TestWorkflow
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: |
          $version = ("${{github.ref_name}}").Remove(0, 1)
          echo "VERSION=$version" >> $env:GITHUB_ENV
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION}}
          release_name: ${{env.VERSION}}
          draft: false
          prerelease: false
      - name: Download and Rename File
        run: |
          curl -L -o Geta.Optimizely.Categories.1.1.3.nupkg "https://nuget.pkg.github.com/Geta/download/Geta.Optimizely.Categories/1.1.3/Geta.Optimizely.Categories.1.1.3.nupkg"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Geta.Optimizely.Categories.1.1.3.nupkg
          asset_name: Geta.Optimizely.Categories.1.1.3.nupkg
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}